- name: install mariadb package (Debian)
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Debian"

- name: install mariadb package (CentOS)
  apt:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"
