---
- hosts: all
  become: true
  tasks:
    - name: create abhistar user
      tags: always
      user:
        name: abhistar
        groups: root
    - name: add ssh key for abhistar
      tags: always
      ansible.builtin.authorized_key:
        user: abhistar
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOd3XPLEGz3/4P8m8HXJ1ANO5sU/JQSPjxc6BNSSFT5Q abhishek@astra"
    - name: add sudoers file for abhistar
      copy:
        src: ../Files/sudoer_abhistar
        dest: /etc/sudoers.d/abhistar
        owner: root
        group: root
        mode: 0440
# COMMAND: ansible-playbook --ask-become-pass -i inventory_target Playbooks/create_user.yml
# COMMAND: ansible-playbook --tags debian --ask-become-pass -i inventory_target Playbooks/create_user.yml
# COMMAND: ansible-playbook --tags "debian,db" --ask-become-pass -i inventory_target Playbooks/create_user.yml
