---
- hosts: all
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes
      when: ansible_distrubution == ["Debian", "Ubuntu"]

    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distrubution == "Debian"

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distrubution == "Debian"

    - name: update repository index
      dnf:
        update_cache: yes
      when: ansible_distrubution == ["CentOS"]

    - name: install httpd package
      apt:
        name: httpd
        state: latest
      when: ansible_distrubution == "CentOS"

    - name: add php support for apache
      apt:
        name: php
        state: latest
      when: ansible_distrubution == "CentOS"
# COMMAND: ansible-playbook --ask-become-pass Playbooks/install_apache2.yml
