---
- hosts: all
  become: true
  tasks:
    - name: install apache and php
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
# COMMAND: ansible-playbook --ask-become-pass Playbooks/install_apache3.yml
