---
- hosts: all
  become: true
  pre_tasks:
    - name: update repo cache (Debian)
      apt:
        update_cache: yes
      changed_when: false
      when: ansansible_distrubution == "Debian"
    - name: update repo cache (CentOS)
      dnf:
        update_cache: yes
      changed_when: false
      when: ansansible_distrubution == "CentOS"

- hosts: web-servers
  become: true
  tasks:
    - name: install apache2 package (Debian)
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distrubution == "Debian"
    - name: install httpd package (CentOS)
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distrubution == "CentOS"

- hosts: db-servers
  become: true
  tasks:
    - name: install mariadb package (Debian)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distrubution == "Debian"
    - name: install mariadb package (CentOS)
      apt:
        name: mariadb
        state: latest
      when: ansible_distrubution == "CentOS"

- hosts: file-servers
  become: true
  tasks:
    - name: install samba package (Debian)
      apt:
        name: samba
        state: latest
# COMMAND: ansible-playbook --ask-become-pass -i inventory_target Playbooks/site.yml
