- name: create abhistar user
  tags: always
  user:
    name: abhistar
    groups: root
- name: add ssh key for abhistar
  tags: always
  authorized_keys:
    user: abhistar
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOd3XPLEGz3/4P8m8HXJ1ANO5sU/JQSPjxc6BNSSFT5Q abhishek@astra"
- name: add sudoers file for abhistar
  copy:
    src: ../Files/sudoer_abhistar
    dest: /etc/sudoers.d/abhistar
    owner: root
    group: root
    mode: 0440
